#!/bin/bash
#
#SBATCH --job-name=MH2O4w
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 120:00:00
#SBATCH --mem-per-cpu 855000
#SBATCH -o /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/milkshake_vs_h2O/outputs/4w_milk_vs_h2O_out_a.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/milkshake_vs_h2O/outputs/4w_milk_vs_h2O_err_a.txt

~/anaconda3/bin/python /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/milkshake_vs_h2O/4w.py