#!/bin/bash
#
#SBATCH --job-name=4wb1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 120:00:00
#SBATCH --mem-per-cpu 505000
#SBATCH -o /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/milkshake_vs_h2O/outputs/all_b1_milk_vs_h2O_out_a.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/milkshake_vs_h2O/outputs/all_b1_milk_vs_h2O_err_a.txt

~/anaconda3/bin/python /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/milkshake_vs_h2O/waves1-4_all.py