#!/bin/bash
#
#SBATCH --job-name=HF_LS_W1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 120:00:00
#SBATCH --mem-per-cpu 150000
#SBATCH -o /projects/niblab/bids_projects/Experiments/ChocoData/error_files/SVM_HF_LS_vs_h2O_w2_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/ChocoData/error_files/SVM_HF_LS_vs_h2O_w2_err.txt

~/anaconda3/bin/python /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/HF_LS_H2O_SVM_W2.py