#!/bin/bash
#
#SBATCH --job-name=4W_LF_LS_PARTB
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 120:00:00
#SBATCH --mem-per-cpu 375000
#SBATCH -o /projects/niblab/bids_projects/Experiments/ChocoData/error_files/4w_part2_LF_LS_vs_h2O_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/ChocoData/error_files/4w_part2_LF_LS_vs_h2O_err.txt

~/anaconda3/bin/python /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/LF_LS_vs_h2O/4w_part2.py