#!/bin/bash
#
#SBATCH --job-name=W1p_LF_LS
#SBATCH -N 2
#SBATCH -c 2
#SBATCH -t 120:00:00
#SBATCH --mem-per-cpu 455000
#SBATCH -o /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/LF_LS_vs_h2O/outputs/w1_LF_LS_vs_h2O_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/LF_LS_vs_h2O/outputs/w1_LF_LS_vs_h2O_err.txt

~/anaconda3/bin/python /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/LF_LS_vs_h2O/w1_partial.py