#!/bin/bash
#
#SBATCH --job-name=4W_PARTA
#SBATCH -N 2
#SBATCH -c 2
#SBATCH -t 120:00:00
#SBATCH --mem-per-cpu 150000
#SBATCH -o /projects/niblab/bids_projects/Experiments/ChocoData/error_files/4w_part1_HF_LS_vs_h2O_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/ChocoData/error_files/4w_part1_HF_LS_vs_h2O_err.txt

~/anaconda3/bin/python /projects/niblab/bids_projects/Experiments/ChocoData/derivatives/code/decoding/HF_LS_vs_h2O/4w_part1_HF_LS_vs_h2O.py